name: Build & Deploy Azure Function

on:
  push:
    branches:
      - main        # of de branch die je gebruikt

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-functions

      - name: Archive function app
        run: zip -r functionapp.zip . -x ".git/*"

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: <fa-lenferink-ai-d2-demo> 
          package: functionapp.zip
