name: Build and deploy Python Function to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'      # Root van je repo, waar function_app.py en requirements.txt liggen
  PYTHON_VERSION: '3.11'                   # Wheels voor grpcio e.d. bestaan meestal voor 3.11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive function app
        run: zip -r functionapp.zip . -x "venv/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: functionapp.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp

      - name: Unzip artifact
        run: unzip functionapp.zip -d functionapp

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'fa-lenferink-ai-d2-demo'                   # jouw Function App naam
          slot-name: 'Production'
          package: './functionapp'                              # de uitgepakte map
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_93BC30BD537F4B828DC4446BC54D17BB }}

